# Nom du workflow qui apparaîtra dans l'onglet "Actions" de votre repo
name: Build macOS Installers

# Déclencheur : ce workflow s'exécute à chaque "push" sur la branche "main"
on:
  push:
    branches: [ main ]
  # Permet aussi de le lancer manuellement depuis l'interface de GitHub
  workflow_dispatch:

jobs:
  build-macos:
    # Stratégie de Matrice : exécute les mêmes étapes sur les deux architectures Mac
    strategy:
      matrix:
        include:
          - os: macos-14
            platform: Mac-ARM
          - os: macos-13
            platform: Mac-Intel

    # Utilise la machine virtuelle définie dans la matrice
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Importer le certificat combiné et vérifier les identités
      - name: Import and Verify Combined Apple Certificate
        env:
          MACOS_CERTS_P12: ${{ secrets.MACOS_CERTS_P12 }}
          MACOS_CERTS_PASSWORD: ${{ secrets.MACOS_CERTS_PASSWORD }}
        run: |
          # Vérification du secret
          if [ -z "$MACOS_CERTS_P12" ]; then echo "::error::Secret MACOS_CERTS_P12 is empty or not set."; exit 1; fi

          # Importation du certificat combiné
          echo "$MACOS_CERTS_P12" | base64 --decode > combined.p12
          security create-keychain -p temp build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p temp build.keychain
          # On autorise l'accès à tous les outils de signature nécessaires
          security import combined.p12 -k build.keychain -P "$MACOS_CERTS_PASSWORD" -A -T /usr/bin/codesign -T /usr/bin/productsign -T /usr/bin/pkgbuild
          security set-key-partition-list -S apple-tool:,apple: -s -k temp build.keychain

          # Vérification que les deux identités sont bien présentes
          echo "--- Available Signing Identities ---"
          security find-identity -v -p codesigning build.keychain
          echo "------------------------------------"
          
          APP_IDENTITY=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          if [ -z "$APP_IDENTITY" ]; then
            echo "::error::Developer ID Application certificate not found in combined P12."
            exit 1
          fi
          
          INSTALLER_IDENTITY=$(security find-identity -v build.keychain | grep "Developer ID Installer")
          if [ -z "$INSTALLER_IDENTITY" ]; then
            echo "::error::Developer ID Installer certificate not found in combined P12."
            exit 1
          fi
          
          echo "✅ Both Application and Installer certificates found in the keychain."

      # 3. Configure l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 4. Crée l'environnement virtuel et installe les dépendances
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt
        shell: bash

      # 5. Construire l'API avec PyInstaller
      - name: Build API with PyInstaller
        run: |
          source venv/bin/activate
          python -m PyInstaller --noconfirm --clean --name PremiereCopilot --console --hidden-import=scipy._cyutility backend/api.py
        shell: bash

      # 6. Signer l'exécutable de l'API et ses composants
      - name: Sign the API Executable
        run: |
          SIGNING_IDENTITY=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application" | head -n 1 | sed -e 's/.*"\(.*\)"/\1/')
          echo "Using Application signing identity: $SIGNING_IDENTITY"
          find dist/PremiereCopilot -type f \( -name "*.dylib" -o -name "*.so" \) -exec codesign --force --sign "$SIGNING_IDENTITY" --options runtime {} \;
          codesign --force --sign "$SIGNING_IDENTITY" --options runtime dist/PremiereCopilot

      # 7. Préparer les fichiers pour le ZXP
      - name: Prepare files for ZXP
        run: |
          mkdir -p frontend/PremiereGPTBeta/js/libs/PremiereCopilotAPI
          cp -R dist/PremiereCopilot frontend/PremiereGPTBeta/js/libs/PremiereCopilotAPI/

      # 8. Créer et signer le ZXP
      - name: Create and Sign ZXP
        working-directory: ./frontend
        run: |
          chmod +x ./ZXPSignCmd
          ./ZXPSignCmd -selfSignedCert "FR" "France" "PremiereCopilot" "PremiereGPTBeta" "plugin2025" "PremiereGPTBeta.p12" -email "admin@premierecopilot.com" -orgUnit "PremiereGPTBeta" -validityDays 3G50
          ./ZXPSignCmd -sign "./PremiereGPTBeta" "./PremiereGPTBeta.zxp" "./PremiereGPTBeta.p12" "plugin2025"
          ./ZXPSignCmd -verify "./PremiereGPTBeta.zxp" -certinfo

      # 9. Construire et signer l'installeur PKG
      - name: Build and Sign PKG Installer
        run: |
          mkdir -p build/pkg_root/PremiereGPTBeta
          unzip frontend/PremiereGPTBeta.zxp -d build/pkg_root/PremiereGPTBeta
          mkdir -p build/scripts
          chmod +x preinstall.sh postinstall.sh
          cp preinstall.sh build/scripts/preinstall
          cp postinstall.sh build/scripts/postinstall
          
          echo "--- Available identities in build.keychain ---"
          security find-identity -v build.keychain
          echo "---------------------------------------------"

          # Correction : On cherche dans toutes les identités (-v) et non plus seulement celles pour la signature de code (-p codesigning)
          SIGNING_IDENTITY=$(security find-identity -v build.keychain | grep "Developer ID Installer" | head -n 1 | sed -e 's/.*"\(.*\)"/\1/')
          
          if [ -z "$SIGNING_IDENTITY" ]; then
            echo "::error::Developer ID Installer identity not found."
            exit 1
          fi

          echo "Using Installer signing identity: $SIGNING_IDENTITY"
          pkgbuild --root build/pkg_root \
                   --install-location "/Library/Application Support/Adobe/CEP/extensions" \
                   --scripts build/scripts \
                   --identifier com.trial17.premierecopilot \
                   --version 1.0 \
                   --sign "$SIGNING_IDENTITY" \
                   build/PremiereCopilot-Installer.pkg

      # 10. Uploader l'artefact final
      - name: Upload PKG Installer
        uses: actions/upload-artifact@v4
        with:
          name: PremiereCopilot-Installer-${{ matrix.platform }}
          path: build/PremiereCopilot-Installer.pkg
